baseurl = "http://startup.school.nz/"
languageCode = "en-nz"
title = "startup.school.nz"
theme = "hugo-future-imperfect"
preserveTaxonomyNames = true
paginate = 3
googleAnalytics = ""
publishdir = "public"

[params]
    # Sets the meta tag description, usually reserved for the main page
    description          = "we believe connecting people with the tools & opportunities they need to do work they care about will create healty & resilient communities"
    # This will appear on the top left of the navigation bar
    navbarTitle          = "startup.school.nz"
    # Social media buttons that appear on the sidebar
    socialAppearAtTop    = true
    socialAppearAtBottom = true
    # set this to the section name if section is not post
    viewMorePostLink     = "/blog/"

# Optional Params
    categoriesByCount    = true
    includeReadingTime   = true
    # The set of favicons used are based on the write-up from this link:
    # https://github.com/audreyr/favicon-cheat-sheet
    # Please see the favicon partial template for more information
    loadFavicon          = false
    faviconVersion       = ""

    # Load custom CSS or JavaScript files. This replaces the deprecated params
    # minifiedFilesCSS and minifiedFilesJS. The variable is an array so that you
    # can load multiple files if necessary. You can also load the standard theme
    # files by adding the value, "default".
    # customCSS            = ["default", "/path/to/file"]
    # customJS             = ["default", "/path/to/file"]

    # Loading min files for exampleSite
    # customCSS            = ["/css/main.min.css"]
    # customJS             = ["/js/main.min.js"]

# parms.intro will appear on the sidebar
# This is optional, but it's suggested to use
[params.intro]
    header    = "startup school"
    paragraph = "we believe connecting people with the tools & opportunities they need to do work they care about will create healty & resilient communities"
    about     = "startup.school.nz is a bunch of people that are passionate to transform New Zealand into startup central. We use the term _startup_ very loose and really focus on businesses that have the potential to have a substantial impact on their community."

# This will also appear on the sidebar.
# A width of less than 100px is recommended
# This is optional
[params.intro.pic]
    src       = "/img/logo.png"
    # modify your picture in the shape of a circle or
    # future imperfect's hexagonal shape
    circle    = false
    imperfect = true
    width     = ""
    alt       = "startup.school.nz"

# Adjust the amount of recent posts on the sidebar.
# This is optional. The default value 5 will be used
[params.postAmount]
    sidebar = 2

# Set up your menu items in the navigation bar
# You can use identifier to prepend a font awesome icon to your text
[[menu.main]]
    name = "Blog"
    url = "/blog"
    identifier = "fa fa-newspaper-o"
    weight = 1

[[menu.main]]
    name = "Deep Dive Workshops"
    url = "/deep_dive/workshops"
    weight = 2

[[menu.main]]
    name = "meetups"
    url = "http://www.meetup.com/localfoundation"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 3

# Insert your username and the icon will apear on the page as long as
# socialAppearAtTop or socialAppearAtBottom is set to true in the params area
# The social media icons will appear on the sidebar
[social]
    github          = ""
    bitbucket       = ""
    jsfiddle        = ""
    codepen         = ""
    foursquare      = ""
    dribbble        = ""
    deviantart      = ""
    behance         = ""
    flickr          = ""
    instagram       = ""
    youtube         = ""
    vimeo           = ""
    vine            = ""
    medium          = ""
    wordpress       = ""
    tumblr          = ""
    xing            = ""
    linkedin        = ""
    slideshare      = ""
    stackoverflow   = ""
    reddit          = ""
    pinterest       = ""
    googleplus      = ""
    facebook        = ""
    facebook_admin  = ""
    twitter_domain  = ""
    twitter         = ""
    email           = ""
